### ISSUE TITLE
set up connection for RESTAURANT api

### ISSUE THREAD

**Issue by setocourtney** [crispysodium/crave_masters#21]

**Comment by crispysodium** [comment]
update: yelpAPI does not support CORS so we need to potentially find a new restaurant search API

**Comment by crispysodium** [comment]
proposal: use alcohol recs as an alternative

**Comment by crispysodium** [comment]
found this free API: https://opentable.herokuapp.com/
note: it only allows to search for restaurants by name, location, and price. Does not pull category as far as I can tell.

**Comment by crispysodium** [comment]
zomato API: https://developers.zomato.com/api?lang=en
note: need to generate free API key, but running into some trouble (does pull by cuisine, so most optimal)

**Comment by crispysodium** [comment]
settled on foursquare API
docs
https://developer.foursquare.com/docs/api
test API
https://foursquare.com/developers/explore#req=venues%2Fcategories
endpoints
https://developer.foursquare.com/docs/api/endpoints
categories - Food, and then search by ethnicity
https://developer.foursquare.com/docs/api/venues/categories
