### ISSUE TITLE
Figure out categories

### ISSUE THREAD

**Issue by Brigmu** [crispysodium/crave_masters#34]
Compare recipe and restaurant categories to determine shared categories to use:

Recipe Categories: American
British
Canadian
Chinese
Dutch
Egyptian
French
Greek
Indian
Irish
Italian
Jamaican
Japanese
Kenyan
Malaysian
Mexican
Morrocan
Russian
Spanish
Thai
Tunissian
Turkish
Unknown
Vietnamese

**Comment by crispysodium** [comment]
chosen categories:
Italian
Chinese
Mexican
American

added:
French
Vietnamese
Thai
Indian
Greek
Japanese
